# Generated by Django 2.2.15 on 2020-08-18 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0007_auto_20200819_0120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='timestamp',
        ),
        migrations.DeleteModel(
            name='TweetLike',
        ),
    ]
